export const APP_NAME = 'OmniPaw'
export const APP_ID = 'com.omnipaw.desktop'
export const CAT_APPEARANCE_ASSET_PROTOCOL = 'omnipaw-cat-asset'
export const BACKGROUND_ASSET_PROTOCOL = 'omnipaw-background'

export const SYSTEM_SESSION_IDS = {
  cron: 'cron-default',
} as const

export const IPC_CHANNELS = {
  app: {
    getInfo: 'app:get-info',
    openSettingsDirectory: 'app:open-settings-directory',
    openChatSession: 'app:open-chat-session',
    navigateToChat: 'app:navigate-to-chat',
  },
  window: {
    getState: 'window:get-state',
    minimize: 'window:minimize',
    toggleMaximize: 'window:toggle-maximize',
    close: 'window:close',
    stateChanged: 'window:state-changed',
  },
  logging: {
    write: 'logging:write',
    status: 'logging:status',
    openLocation: 'logging:open-location',
    export: 'logging:export',
  },
  cat: {
    show: 'cat:show',
    hide: 'cat:hide',
    toggleVisibility: 'cat:toggle-visibility',
    setState: 'cat:set-state',
    togglePanel: 'cat:toggle-panel',
    dragStart: 'cat:drag-start',
    dragMove: 'cat:drag-move',
    dragEnd: 'cat:drag-end',
    reportState: 'cat:renderer-state',
    commandState: 'cat:state-changed',
    observationReaction: 'cat:observation-reaction',
    openObservationSource: 'cat:open-observation-source',
    showBubble: 'cat:show-bubble',
    dismissBubble: 'cat:dismiss-bubble',
    bubbleReady: 'cat:bubble-ready',
    bubbleEvent: 'cat:bubble-event',
    bubblePlacement: 'cat:bubble-placement',
  },
  catAppearance: {
    current: 'cat-appearance:current',
    getPack: 'cat-appearance:get-pack',
    list: 'cat-appearance:list',
    refresh: 'cat-appearance:refresh',
    importPack: 'cat-appearance:import-pack',
    deletePack: 'cat-appearance:delete-pack',
    setActive: 'cat-appearance:set-active',
    changed: 'cat-appearance:changed',
  },
  catPanel: {
    placement: 'cat-panel:placement',
    open: 'cat-panel:open',
    getActiveSession: 'cat-panel:get-active-session',
    setActiveSession: 'cat-panel:set-active-session',
    activeSessionChanged: 'cat-panel:active-session-changed',
    getDraft: 'cat-panel:get-draft',
    stageDraftAttachments: 'cat-panel:stage-draft-attachments',
    clearDraft: 'cat-panel:clear-draft',
    draftChanged: 'cat-panel:draft-changed',
  },
  catNotification: {
    event: 'cat-notification:event',
    close: 'cat-notification:close',
    viewResult: 'cat-notification:view-result',
  },
  catPet: {
    getState: 'cat-pet:get-state',
    performAction: 'cat-pet:perform-action',
    changed: 'cat-pet:changed',
  },
  settings: {
    load: 'settings:load',
    save: 'settings:save',
    reset: 'settings:reset',
    status: 'settings:status',
    pickBackgroundImage: 'settings:pick-background-image',
    changed: 'settings:changed',
  },
  shortcuts: {
    status: 'shortcuts:status',
    setCaptureMode: 'shortcuts:set-capture-mode',
    changed: 'shortcuts:changed',
  },
  memory: {
    list: 'memory:list',
    search: 'memory:search',
    inspect: 'memory:inspect',
    create: 'memory:create',
    update: 'memory:update',
    archive: 'memory:archive',
    delete: 'memory:delete',
    setImportance: 'memory:set-importance',
    listProposals: 'memory:list-proposals',
    updateProposal: 'memory:update-proposal',
    getSettings: 'memory:get-settings',
    updateSettings: 'memory:update-settings',
  },
  companionRole: {
    importCard: 'companion-role:import-card',
  },
  observation: {
    permissionStatus: 'observation:permission-status',
    status: 'observation:status',
    start: 'observation:start',
    stop: 'observation:stop',
    trigger: 'observation:trigger',
    changed: 'observation:changed',
    notification: 'observation:notification',
  },
  chat: {
    listSessions: 'chat:list-sessions',
    createSession: 'chat:create-session',
    getSession: 'chat:get-session',
    updateSession: 'chat:update-session',
    deleteSession: 'chat:delete-session',
    listMessages: 'chat:list-messages',
    sendMessage: 'chat:send-message',
    abortRun: 'chat:abort-run',
    approveToolCall: 'chat:approve-tool-call',
    editMessage: 'chat:edit-message',
    regenerateMessage: 'chat:regenerate-message',
    uploadAttachment: 'chat:upload-attachment',
    getAttachmentPreview: 'chat:get-attachment-preview',
    sessionChanged: 'chat:session-changed',
    streamEvent: 'chat:stream-event',
    streamToken: 'chat:stream-token',
    streamDone: 'chat:stream-done',
  },
  provider: {
    load: 'provider:load',
    status: 'provider:status',
    list: 'provider:list',
    listPresets: 'provider:list-presets',
    createFromPreset: 'provider:create-from-preset',
    upsertSource: 'provider:upsert-source',
    upsertModel: 'provider:upsert-model',
    upsert: 'provider:upsert',
    deleteSource: 'provider:delete-source',
    deleteModel: 'provider:delete-model',
    delete: 'provider:delete',
    setDefaultModel: 'provider:set-default-model',
    setFallbackModels: 'provider:set-fallback-models',
    setTitleModel: 'provider:set-title-model',
    setEmbeddingModel: 'provider:set-embedding-model',
    setObservationModels: 'provider:set-observation-models',
    test: 'provider:test',
    listModels: 'provider:list-models',
    refreshModels: 'provider:refresh-models',
    setSessionModel: 'provider:set-session-model',
    openAICodexOAuthStatus: 'provider:openai-codex-oauth-status',
    openAICodexOAuthLogin: 'provider:openai-codex-oauth-login',
    openAICodexOAuthLogout: 'provider:openai-codex-oauth-logout',
    changed: 'provider:changed',
  },
  skill: {
    list: 'skill:list',
    refresh: 'skill:refresh',
    setEnabled: 'skill:set-enabled',
    importSkill: 'skill:import',
    changed: 'skill:changed',
  },
  cron: {
    list: 'cron:list',
    create: 'cron:create',
    update: 'cron:update',
    delete: 'cron:delete',
    runNow: 'cron:run-now',
    listRuns: 'cron:list-runs',
    changed: 'cron:changed',
  },
  tools: {
    list: 'tools:list',
    setEnabled: 'tools:set-enabled',
  },
  workspace: {
    status: 'workspace:status',
    listFiles: 'workspace:list-files',
    readFile: 'workspace:read-file',
    exportFile: 'workspace:export-file',
    revealFile: 'workspace:reveal-file',
    deleteFile: 'workspace:delete-file',
    cleanup: 'workspace:cleanup',
  },
  terminalProcess: {
    list: 'terminal-process:list',
    get: 'terminal-process:get',
    kill: 'terminal-process:kill',
  },
  mcp: {
    listServers: 'mcp:list-servers',
    saveServer: 'mcp:save-server',
    deleteServer: 'mcp:delete-server',
    setServerEnabled: 'mcp:set-server-enabled',
    refreshServer: 'mcp:refresh-server',
    listTools: 'mcp:list-tools',
    changed: 'mcp:changed',
  },
  omniinfer: {
    getStatus: 'omniinfer:get-status',
    start: 'omniinfer:start',
    stop: 'omniinfer:stop',
    selectModel: 'omniinfer:select-model',
    unloadModel: 'omniinfer:unload-model',
    setThinking: 'omniinfer:set-thinking',
    listSupportedModels: 'omniinfer:list-supported-models',
    statusChanged: 'omniinfer:status-changed',
    log: 'omniinfer:log',
    getLogsPath: 'omniinfer:get-logs-path',
    pickLocalGguf: 'omniinfer:pick-local-gguf',
    pickInstallDir: 'omniinfer:pick-install-dir',
    rescanModels: 'omniinfer:rescan-models',
  },
} as const
