export const APP_NAME = 'OpenOmniClaw'

export const IPC_CHANNELS = {
  app: {
    getInfo: 'app:get-info',
  },
  logging: {
    write: 'logging:write',
    status: 'logging:status',
  },
  cat: {
    show: 'cat:show',
    hide: 'cat:hide',
    toggleVisibility: 'cat:toggle-visibility',
    setState: 'cat:set-state',
    togglePanel: 'cat:toggle-panel',
    dragStart: 'cat:drag-start',
    dragMove: 'cat:drag-move',
    dragEnd: 'cat:drag-end',
    reportState: 'cat:renderer-state',
    commandState: 'cat:state-changed',
  },
  catPanel: {
    placement: 'cat-panel:placement',
  },
  settings: {
    load: 'settings:load',
    save: 'settings:save',
    reset: 'settings:reset',
    status: 'settings:status',
    changed: 'settings:changed',
  },
  chat: {
    listSessions: 'chat:list-sessions',
    createSession: 'chat:create-session',
    getSession: 'chat:get-session',
    updateSession: 'chat:update-session',
    deleteSession: 'chat:delete-session',
    listMessages: 'chat:list-messages',
    sendMessage: 'chat:send-message',
    abortRun: 'chat:abort-run',
    editMessage: 'chat:edit-message',
    regenerateMessage: 'chat:regenerate-message',
    uploadAttachment: 'chat:upload-attachment',
    getAttachmentPreview: 'chat:get-attachment-preview',
    sessionChanged: 'chat:session-changed',
    streamEvent: 'chat:stream-event',
    streamToken: 'chat:stream-token',
    streamDone: 'chat:stream-done',
  },
  provider: {
    load: 'provider:load',
    status: 'provider:status',
    list: 'provider:list',
    listPresets: 'provider:list-presets',
    createFromPreset: 'provider:create-from-preset',
    upsertSource: 'provider:upsert-source',
    upsertModel: 'provider:upsert-model',
    upsert: 'provider:upsert',
    deleteSource: 'provider:delete-source',
    deleteModel: 'provider:delete-model',
    delete: 'provider:delete',
    setDefaultModel: 'provider:set-default-model',
    setFallbackModels: 'provider:set-fallback-models',
    setTitleModel: 'provider:set-title-model',
    test: 'provider:test',
    listModels: 'provider:list-models',
    refreshModels: 'provider:refresh-models',
    setSessionModel: 'provider:set-session-model',
    changed: 'provider:changed',
  },
  skill: {
    list: 'skill:list',
    refresh: 'skill:refresh',
    setEnabled: 'skill:set-enabled',
    importSkill: 'skill:import',
    changed: 'skill:changed',
  },
  cron: {
    list: 'cron:list',
  },
  tools: {
    list: 'tools:list',
    setEnabled: 'tools:set-enabled',
  },
  mcp: {
    listServers: 'mcp:list-servers',
    saveServer: 'mcp:save-server',
    deleteServer: 'mcp:delete-server',
    setServerEnabled: 'mcp:set-server-enabled',
    refreshServer: 'mcp:refresh-server',
    listTools: 'mcp:list-tools',
    changed: 'mcp:changed',
  },
} as const
