export const APP_NAME = 'OpenOmniClaw'

export const SYSTEM_SESSION_IDS = {
  cron: 'cron-default',
} as const

export const IPC_CHANNELS = {
  app: {
    getInfo: 'app:get-info',
    openChatSession: 'app:open-chat-session',
    navigateToChat: 'app:navigate-to-chat',
  },
  logging: {
    write: 'logging:write',
    status: 'logging:status',
  },
  cat: {
    show: 'cat:show',
    hide: 'cat:hide',
    toggleVisibility: 'cat:toggle-visibility',
    setState: 'cat:set-state',
    togglePanel: 'cat:toggle-panel',
    dragStart: 'cat:drag-start',
    dragMove: 'cat:drag-move',
    dragEnd: 'cat:drag-end',
    reportState: 'cat:renderer-state',
    commandState: 'cat:state-changed',
    observationReaction: 'cat:observation-reaction',
    openObservationSource: 'cat:open-observation-source',
    showBubble: 'cat:show-bubble',
    dismissBubble: 'cat:dismiss-bubble',
    bubbleReady: 'cat:bubble-ready',
    bubbleEvent: 'cat:bubble-event',
    bubblePlacement: 'cat:bubble-placement',
  },
  catPanel: {
    placement: 'cat-panel:placement',
    open: 'cat-panel:open',
    getActiveSession: 'cat-panel:get-active-session',
    setActiveSession: 'cat-panel:set-active-session',
    activeSessionChanged: 'cat-panel:active-session-changed',
    getDraft: 'cat-panel:get-draft',
    stageDraftAttachments: 'cat-panel:stage-draft-attachments',
    clearDraft: 'cat-panel:clear-draft',
    draftChanged: 'cat-panel:draft-changed',
  },
  catNotification: {
    event: 'cat-notification:event',
    close: 'cat-notification:close',
    viewResult: 'cat-notification:view-result',
  },
  settings: {
    load: 'settings:load',
    save: 'settings:save',
    reset: 'settings:reset',
    status: 'settings:status',
    changed: 'settings:changed',
  },
  observation: {
    permissionStatus: 'observation:permission-status',
    status: 'observation:status',
    start: 'observation:start',
    stop: 'observation:stop',
    trigger: 'observation:trigger',
    changed: 'observation:changed',
    notification: 'observation:notification',
  },
  chat: {
    listSessions: 'chat:list-sessions',
    createSession: 'chat:create-session',
    getSession: 'chat:get-session',
    updateSession: 'chat:update-session',
    deleteSession: 'chat:delete-session',
    listMessages: 'chat:list-messages',
    sendMessage: 'chat:send-message',
    abortRun: 'chat:abort-run',
    approveToolCall: 'chat:approve-tool-call',
    editMessage: 'chat:edit-message',
    regenerateMessage: 'chat:regenerate-message',
    uploadAttachment: 'chat:upload-attachment',
    getAttachmentPreview: 'chat:get-attachment-preview',
    sessionChanged: 'chat:session-changed',
    streamEvent: 'chat:stream-event',
    streamToken: 'chat:stream-token',
    streamDone: 'chat:stream-done',
  },
  provider: {
    load: 'provider:load',
    status: 'provider:status',
    list: 'provider:list',
    listPresets: 'provider:list-presets',
    createFromPreset: 'provider:create-from-preset',
    upsertSource: 'provider:upsert-source',
    upsertModel: 'provider:upsert-model',
    upsert: 'provider:upsert',
    deleteSource: 'provider:delete-source',
    deleteModel: 'provider:delete-model',
    delete: 'provider:delete',
    setDefaultModel: 'provider:set-default-model',
    setFallbackModels: 'provider:set-fallback-models',
    setTitleModel: 'provider:set-title-model',
    setObservationModels: 'provider:set-observation-models',
    test: 'provider:test',
    listModels: 'provider:list-models',
    refreshModels: 'provider:refresh-models',
    setSessionModel: 'provider:set-session-model',
    changed: 'provider:changed',
  },
  skill: {
    list: 'skill:list',
    refresh: 'skill:refresh',
    setEnabled: 'skill:set-enabled',
    importSkill: 'skill:import',
    changed: 'skill:changed',
  },
  cron: {
    list: 'cron:list',
    create: 'cron:create',
    update: 'cron:update',
    delete: 'cron:delete',
    runNow: 'cron:run-now',
    listRuns: 'cron:list-runs',
    changed: 'cron:changed',
  },
  tools: {
    list: 'tools:list',
    setEnabled: 'tools:set-enabled',
  },
  workspace: {
    status: 'workspace:status',
    listFiles: 'workspace:list-files',
    readFile: 'workspace:read-file',
    exportFile: 'workspace:export-file',
    deleteFile: 'workspace:delete-file',
    cleanup: 'workspace:cleanup',
  },
  terminalProcess: {
    list: 'terminal-process:list',
    get: 'terminal-process:get',
    kill: 'terminal-process:kill',
  },
  mcp: {
    listServers: 'mcp:list-servers',
    saveServer: 'mcp:save-server',
    deleteServer: 'mcp:delete-server',
    setServerEnabled: 'mcp:set-server-enabled',
    refreshServer: 'mcp:refresh-server',
    listTools: 'mcp:list-tools',
    changed: 'mcp:changed',
  },
  persona: {
    load: 'persona:load',
    status: 'persona:status',
    list: 'persona:list',
    create: 'persona:create',
    update: 'persona:update',
    delete: 'persona:delete',
    setDefault: 'persona:set-default',
    changed: 'persona:changed',
  },
  tavern: {
    load: 'tavern:load',
    status: 'tavern:status',
    list: 'tavern:list',
    importCharacter: 'tavern:import-character',
    createCharacter: 'tavern:create-character',
    updateCharacter: 'tavern:update-character',
    deleteCharacter: 'tavern:delete-character',
    setCharacterEnabled: 'tavern:set-character-enabled',
    createLorebook: 'tavern:create-lorebook',
    updateLorebook: 'tavern:update-lorebook',
    deleteLorebook: 'tavern:delete-lorebook',
    setLorebookEnabled: 'tavern:set-lorebook-enabled',
    exportCharacterAsPersona: 'tavern:export-character-persona',
    createSession: 'tavern:create-session',
    updateSessionBinding: 'tavern:update-session-binding',
    changed: 'tavern:changed',
  },
} as const
